update pre-commit hooks, fix new pylint warnings
Note: not updating mypy past 0.900 because it causes an error:

```
gcpdiag/queries/logs.py:45: error: Library stubs not installed for
"dateutil.parser" (or incompatible with Python 3.9)
gcpdiag/queries/logs.py:45: note: Hint: "python3 -m pip install
types-python-dateutil"
gcpdiag/queries/logs.py:45: note: (or run "mypy --install-types" to
install all missing stub packages)
gcpdiag/queries/logs.py:45: note: See
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Adding types-python-dateutil doesn't fix the issue at the moment.

Change-Id: I7ab17ec43a8b2c5602639c4afe4f1dfaecb75cdd
GitOrigin-RevId: b7419f1942c70b3e40c64413e69e1de247f677a2