Merge "add str repr of RuleModule for more info in exceptions loading rules" -- Branch commit log -- commit ea69c7077c1016d8686ccc5d5fe314b790d51a45 Author:  Rodney Peck <ropeck@google.com> Date:    2024-01-09T13:49:29-08:00
    add str repr of RuleModule for more info in exceptions loading rules

b/318701295

exception in loading shows module repr like this:
  File "/usr/local/google/home/ropeck/gcpdiag/gcpdiag/lint/__init__.py", line 469, in get_rule_by_module_name
    raise RuntimeError(
RuntimeError: module RuleModule:<module 'gcpdiag.lint.lb.bp_2023_001_cloudcdn_for_lb_backend_services' from '/usr/local/google/home/ropeck/gcpdiag/gcpdiag/lint/lb/bp_2023_001_cloudcdn_for_lb_backend_services.py'> has a non-empty second line in the module docstring

Change-Id: I5969eb63668efe47f308858f9e6ca5a5b76875b6
GitOrigin-RevId: 667878e23e930da05a5845a479fe0c3894ebb915